FROM oven/bun:1.1.4-alpine

WORKDIR /app

COPY package.json .
COPY bun.lockb .

RUN bun install --production

COPY src src
COPY tsconfig.json .

ENV NODE_ENV production

EXPOSE 3000

CMD ["bun", "src/index.ts"]
