services:
  frontend:
    build: ./frontend
    container_name: "cardgame-frontend"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: localhost:3000
  backend:
    build: ./backend
    container_name: "cardgame-backend"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    # env_file:
    #   - path: ./backend/.env.docker
    environment:
      DB_HOST: db:27017
      DB_USER: mongodb
      DB_PASSWORD: mongodb
      DB_NAME: cardgame
      DB_URL: mongodb://mongodb:mongodb@db:27017/cardgame?authSource=admin&w=1
      JWT_SECRET: secret
      FRONTEND_URL: localhost:5173
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: "cardgame-db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
